//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChedVX.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainFormStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainFormStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChedVX.Localization.MainFormStrings", typeof(MainFormStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop At Last Note.
        /// </summary>
        public static string AbortAtLastNote {
            get {
                return ResourceManager.GetString("AbortAtLastNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert a blank space at cursor.
        /// </summary>
        public static string AddBlankMeasurement {
            get {
                return ResourceManager.GetString("AddBlankMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Data.
        /// </summary>
        public static string AdditionalData {
            get {
                return ResourceManager.GetString("AdditionalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR DOWN.
        /// </summary>
        public static string AirDown {
            get {
                return ResourceManager.GetString("AirDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR DOWN LEFT.
        /// </summary>
        public static string AirLeftDown {
            get {
                return ResourceManager.GetString("AirLeftDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR UP LEFT.
        /// </summary>
        public static string AirLeftUp {
            get {
                return ResourceManager.GetString("AirLeftUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR DOWN RIGHT.
        /// </summary>
        public static string AirRightDown {
            get {
                return ResourceManager.GetString("AirRightDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR UP RIGHT.
        /// </summary>
        public static string AirRightUp {
            get {
                return ResourceManager.GetString("AirRightUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR UP.
        /// </summary>
        public static string AirUp {
            get {
                return ResourceManager.GetString("AirUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string Artist {
            get {
                return ResourceManager.GetString("Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Information.
        /// </summary>
        public static string BasicInformation {
            get {
                return ResourceManager.GetString("BasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Properties....
        /// </summary>
        public static string BookProperty {
            get {
                return ResourceManager.GetString("BookProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear chart contents....
        /// </summary>
        public static string ClearChartContent {
            get {
                return ResourceManager.GetString("ClearChartContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        public static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy selected lane tilt events.
        /// </summary>
        public static string CopyLaneTiltEvents {
            get {
                return ResourceManager.GetString("CopyLaneTiltEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy selected lane zoom events.
        /// </summary>
        public static string CopyLaneZoomEvents {
            get {
                return ResourceManager.GetString("CopyLaneZoomEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Event.
        /// </summary>
        public static string DeleteEvent {
            get {
                return ResourceManager.GetString("DeleteEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect.
        /// </summary>
        public static string Deselect {
            get {
                return ResourceManager.GetString("Deselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty.
        /// </summary>
        public static string Difficulty {
            get {
                return ResourceManager.GetString("Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division.
        /// </summary>
        public static string Division {
            get {
                return ResourceManager.GetString("Division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit(&amp;E).
        /// </summary>
        public static string EditMenu {
            get {
                return ResourceManager.GetString("EditMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eraser.
        /// </summary>
        public static string Eraser {
            get {
                return ResourceManager.GetString("Eraser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string EventOperation {
            get {
                return ResourceManager.GetString("EventOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File(&amp;F).
        /// </summary>
        public static string FileMenu {
            get {
                return ResourceManager.GetString("FileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse selected notes.
        /// </summary>
        public static string FlipSelectedNotes {
            get {
                return ResourceManager.GetString("FlipSelectedNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide Volume (Global).
        /// </summary>
        public static string GuideVolume {
            get {
                return ResourceManager.GetString("GuideVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help(&amp;H).
        /// </summary>
        public static string HelpMenu {
            get {
                return ResourceManager.GetString("HelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Speed Selection.
        /// </summary>
        public static string HighSpeed {
            get {
                return ResourceManager.GetString("HighSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add AIR with AIR-ACTION.
        /// </summary>
        public static string InsertAirWithAirAction {
            get {
                return ResourceManager.GetString("InsertAirWithAirAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert(&amp;I).
        /// </summary>
        public static string InsertMenu {
            get {
                return ResourceManager.GetString("InsertMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert a single blank space at the beginning.
        /// </summary>
        public static string InsertSingleBlankAtBeginning {
            get {
                return ResourceManager.GetString("InsertSingleBlankAtBeginning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jacket File.
        /// </summary>
        public static string JacketFile {
            get {
                return ResourceManager.GetString("JacketFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard Shortcuts.
        /// </summary>
        public static string KeyboardShortcuts {
            get {
                return ResourceManager.GetString("KeyboardShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Combination.
        /// </summary>
        public static string KeyCombination {
            get {
                return ResourceManager.GetString("KeyCombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Information.
        /// </summary>
        public static string MusicInformation {
            get {
                return ResourceManager.GetString("MusicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Volume.
        /// </summary>
        public static string MusicVolume {
            get {
                return ResourceManager.GetString("MusicVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narrow spacing between lanes.
        /// </summary>
        public static string NarrowLaneSpacing {
            get {
                return ResourceManager.GetString("NarrowLaneSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string NewFile {
            get {
                return ResourceManager.GetString("NewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note Designer.
        /// </summary>
        public static string NotesDesigner {
            get {
                return ResourceManager.GetString("NotesDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset.
        /// </summary>
        public static string Offset {
            get {
                return ResourceManager.GetString("Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste Flipped.
        /// </summary>
        public static string PasteFlipped {
            get {
                return ResourceManager.GetString("PasteFlipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pen.
        /// </summary>
        public static string Pen {
            get {
                return ResourceManager.GetString("Pen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play / Stop.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play(&amp;P).
        /// </summary>
        public static string PlayMenu {
            get {
                return ResourceManager.GetString("PlayMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin.
        /// </summary>
        public static string Plugin {
            get {
                return ResourceManager.GetString("Plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all comments.
        /// </summary>
        public static string RemoveAllComments {
            get {
                return ResourceManager.GetString("RemoveAllComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Selected Events.
        /// </summary>
        public static string RemoveEvents {
            get {
                return ResourceManager.GetString("RemoveEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected lane tilt events.
        /// </summary>
        public static string RemoveLaneTiltEvents {
            get {
                return ResourceManager.GetString("RemoveLaneTiltEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected lane zoom events.
        /// </summary>
        public static string RemoveLaneZoomEvents {
            get {
                return ResourceManager.GetString("RemoveLaneZoomEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected events.
        /// </summary>
        public static string RemoveSelectedEvents {
            get {
                return ResourceManager.GetString("RemoveSelectedEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected measures....
        /// </summary>
        public static string RemoveSelectedMeasurement {
            get {
                return ResourceManager.GetString("RemoveSelectedMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string RemoveSelectedNotes {
            get {
                return ResourceManager.GetString("RemoveSelectedNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset All.
        /// </summary>
        public static string ResetAll {
            get {
                return ResourceManager.GetString("ResetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveFile {
            get {
                return ResourceManager.GetString("SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score Preview.
        /// </summary>
        public static string ScorePreview {
            get {
                return ResourceManager.GetString("ScorePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection.
        /// </summary>
        public static string Selection {
            get {
                return ResourceManager.GetString("Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select to Beginning.
        /// </summary>
        public static string SelectToBeginning {
            get {
                return ResourceManager.GetString("SelectToBeginning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select to End.
        /// </summary>
        public static string SelectToEnd {
            get {
                return ResourceManager.GetString("SelectToEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLIDE (STEP).
        /// </summary>
        public static string SlideStep {
            get {
                return ResourceManager.GetString("SlideStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow Down Preview.
        /// </summary>
        public static string SlowDownPreview {
            get {
                return ResourceManager.GetString("SlowDownPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound File.
        /// </summary>
        public static string SoundFile {
            get {
                return ResourceManager.GetString("SoundFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch color of selected LASER objects.
        /// </summary>
        public static string SwitchLaserColor {
            get {
                return ResourceManager.GetString("SwitchLaserColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Signature Selection.
        /// </summary>
        public static string TimeSignature {
            get {
                return ResourceManager.GetString("TimeSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Info.
        /// </summary>
        public static string VersionInfo {
            get {
                return ResourceManager.GetString("VersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View(&amp;V).
        /// </summary>
        public static string ViewMenu {
            get {
                return ResourceManager.GetString("ViewMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increasing Spacing between lanes.
        /// </summary>
        public static string WidenLaneSpacing {
            get {
                return ResourceManager.GetString("WidenLaneSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom In.
        /// </summary>
        public static string ZoomIn {
            get {
                return ResourceManager.GetString("ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Out.
        /// </summary>
        public static string ZoomOut {
            get {
                return ResourceManager.GetString("ZoomOut", resourceCulture);
            }
        }
    }
}
